learningWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myApp.urls"))
]

myApp/urls.py
from django.urls import path
from .views import CourseListView, LessonListView, LessonDetailView

app_name = "myApp"

urlpatterns = [
    path('', CourseListView.as_view(), name="course-list"),
    path('<str:course_name>/', LessonListView.as_view(), name="lesson-list"),
    path('<str:course_name>/<str:lesson_name>/', LessonDetailView.as_view(), name="lesson-detail")
]

myApp/models.py
from django.db import models

class Course(models.Model):
    course_name = models.CharField(max_length=100)

    def __str__(self):
        return self.course_name
    
class Lesson(models.Model):
    lesson_name = models.CharField(max_length=100)
    course = models.ForeignKey(Course, on_delete=models.CASCADE) # Lesson can have only one course, but Course can have many lessons

    def __str__(self):
        return self.lesson_name

class Article(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    paragraph = models.TextField()
    img = models.ImageField(blank=True, null=True)

class Question(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    question_name = models.CharField(max_length=200)
    explanation = models.TextField()
    img = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.question_name

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, default=None)
    answer_name = models.CharField(max_length=100, blank=True)
    img = models.ImageField(blank=True, null=True)
    isCorrect = models.BooleanField(default=False)

    def __str__(self):
        return self.answer_name

myApp/views.py
from django.views.generic import ListView, DetailView
from .models import Course, Lesson, Article, Question, Answer

class CourseListView(ListView):
    model = Course
    template_name = "myApp/index.html"
    context_object_name = "courses"

class LessonListView(ListView):
    model = Lesson
    template_name = "myApp/lesson_view.html"
    context_object_name = "lessons"

    def get_queryset(self):
        course_name = self.kwargs['course_name'] # Get the selected course from the URL parameter
        lessons = Lesson.objects.filter(course__course_name=course_name) # Filter the lessons queryset by the selected course
        return lessons
    
    # Passing in additional arguments to the template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["course_name"] = self.kwargs['course_name']
        return context
    
class LessonDetailView(DetailView):
    model = Lesson
    template_name = "myApp/lesson_detail_view.html"

    # Done to use str in the url instead of a pk
    def get_object(self):
        course_name = self.kwargs['course_name']
        lesson_name = self.kwargs['lesson_name']
        lesson = Lesson.objects.get(course__course_name=course_name, lesson_name=lesson_name)
        return lesson
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lesson = self.object
        context["lesson_name"] = self.kwargs['lesson_name']
        # lesson.article_set.all() retrieves all the articles related to the current lesson.
        context["articles"] = lesson.article_set.all() # Lesson specific articles
        context["questions"] = lesson.question_set.all()
        return context

myApp/templates/myApp/index.html
{% extends 'myApp/layout.html' %}
{% block body %}
    <h1>Courses</h1>
    {% for course in courses %}
        <a href="{% url 'myApp:lesson-list' course.course_name %}">
            <h2 style="display: inline; margin-right: 30px;">{{ course.course_name }}</h2>
        </a>
    {% endfor %}
{% endblock %}

myApp/templates/myApp/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>

myApp/templates/myApp/lesson_detail_view.html
{% extends 'myApp/layout.html' %}
{% block body %}

    <h1>{{ lesson_name }}</h1>
    {% for article in articles %}
        <div class="article-div" id="article-{{article.pk}}" style="display: none;">
            <p>{{ article.paragraph|linebreaksbr|add:' '|safe }}</p>
        </div>
    {% endfor %}

    {% for question in questions %}
        <div class="question-div" id="question-{{question.pk}}" style="display: none;">
            <form>
                <span>{{ question.question_name }}</span><br>
                {% for answer in question.answer_set.all %}
                    <input type="radio" id="{{ answer.pk }}" name="answer">
                    <label for="answer{{ answer.pk }}">{{answer.answer_name}}</label><br>
                {% endfor %}
                <input type="submit" value="Check">
            </form>
        </div>
    {% endfor %}

    <button id="show-div" onclick="showDiv()" style="display: block;">Continue</button>

    <script>
        function showDiv() {
            let articleDivs = document.querySelectorAll('.article-div');
            for (let i = 0; i < articleDivs.length; i++) {
                if (articleDivs[i].style.display === "none") {
                    articleDivs[i].style.display = "block";
                    return; // exit the function as soon as an article is shown
                }
            }
            
            // If we get here, all the article-div elements have been shown
            let questionDivs = document.querySelectorAll('.question-div');
            questionDivs[0].style.display = "block";
            document.getElementById('show-div').style.display = "none";
        }
    </script>
{% endblock %}

myApp/templates/myApp/lesson_view.html
{% extends 'myApp/layout.html' %}
{% block body %}
    <h1>{{ course_name }} course</h1>
    <h3>LessonView</h3>
    {% for lesson in lessons %}
        <a href="{% url 'myApp:lesson-detail' course_name lesson.lesson_name %}">
            <h2 style="display: inline; margin-right: 30px;">{{ lesson.lesson_name }}</h2>
        </a>
    {% endfor %}
{% endblock %}